---
abstract: 'Client to communicate with beanstalkd server'
author:
  - 'Graham Barr <gbarr@pobox.com>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Beanstalk-Client
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Error: 0
  IO::Socket::INET: 0
  Socket: 0
  YAML::Syck: 0
resources:
  repository: http://git.goingon.net/?p=Beanstalk-Client.git;a=summary
version: 1.00
